Repository dongnae-bangnae/BE, pull requests merged in 2025-07, with the labels that each got.

#9 ✨ [Feat] 스웨거 및 멤버 로그아웃, 탈퇴 로직 구현
  src/main/java/DNBN/spring/service/MemberService/MemberCommandService.java
  src/main/java/DNBN/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/DNBN/spring/web/controller/AuthRestController.java
  src/main/java/DNBN/spring/web/controller/MemberRestController.java
Labels: :sparkles: feature

#14 ✨ [Feat] 카카오 소셜 로그인 구현 완료
  build.gradle
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/DNBN/spring/config/security/KakaoMemberInfo.java
  src/main/java/DNBN/spring/config/security/OAuth2MemberInfo.java
  src/main/java/DNBN/spring/config/security/SecurityConfig.java
  src/main/java/DNBN/spring/config/security/jwt/JwtTokenProvider.java
  src/main/java/DNBN/spring/converter/MemberConverter.java
  src/main/java/DNBN/spring/domain/enums/Provider.java
  src/main/java/DNBN/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/DNBN/spring/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/DNBN/spring/service/OAuth2/CustomOAuth2User.java
  src/main/java/DNBN/spring/service/OAuth2/CustomOAuth2UserService.java
  src/main/java/DNBN/spring/service/OAuth2/KakaoUserInfo.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2FailureHandler.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2UserInfo.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2UserInfoFactory.java
  src/main/java/DNBN/spring/web/dto/AuthResponseDTO.java
  src/main/java/DNBN/spring/web/dto/MemberResponseDTO.java
  src/main/java/DNBN/spring/web/dto/OAuth2RequestDTO.java
  src/main/resources/application.yml
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#15 ✨ [Feat] CORS에러 해결
  .gitignore
  build.gradle
  src/main/java/DNBN/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/DNBN/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/DNBN/spring/config/security/SecurityConfig.java
  src/main/java/DNBN/spring/converter/MemberConverter.java
  src/main/java/DNBN/spring/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/DNBN/spring/domain/Member.java
  src/main/java/DNBN/spring/domain/ProfileImage.java
  src/main/java/DNBN/spring/repository/ArticlePhotoRepository/ArticlePhotoRepository.java
  src/main/java/DNBN/spring/repository/ProfileImageRepository/ProfileImageRepository.java
  src/main/java/DNBN/spring/service/MemberService/MemberCommandService.java
  src/main/java/DNBN/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/DNBN/spring/service/OAuth2/CustomOAuth2UserService.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
  src/main/java/DNBN/spring/web/controller/AuthRestController.java
  src/main/java/DNBN/spring/web/controller/MemberRestController.java
  src/main/java/DNBN/spring/web/dto/MemberRequestDTO.java
Labels: :bug: bug, :sparkles: feature, :ambulance: hotfix

#34 ✨[Feat] 광고 의심 조회/등록/취소 구현
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/exception/DuplicateCategoryException.java
  src/main/java/DNBN/spring/apiPayload/exception/handler/CategoryHandler.java
  src/main/java/DNBN/spring/domain/Article.java
  src/main/java/DNBN/spring/domain/ArticleLike.java
  src/main/java/DNBN/spring/domain/ArticleLikeId.java
  src/main/java/DNBN/spring/domain/ArticleSpam.java
  src/main/java/DNBN/spring/domain/ArticleSpamId.java
  src/main/java/DNBN/spring/domain/Category.java
  src/main/java/DNBN/spring/repository/ArticleLikeRepository/ArticleLikeRepository.java
  src/main/java/DNBN/spring/repository/ArticleSpamRepository/ArticleSpamRepository.java
  src/main/java/DNBN/spring/repository/CategoryRepository/CategoryRepository.java
  src/main/java/DNBN/spring/service/ArticleLikeService/ArticleLikeQueryService.java
  src/main/java/DNBN/spring/service/ArticleLikeService/ArticleLikeService.java
  src/main/java/DNBN/spring/service/ArticleSpamService/ArticleSpamQueryService.java
  src/main/java/DNBN/spring/service/ArticleSpamService/ArticleSpamService.java
  src/main/java/DNBN/spring/service/CategoryService/CategoryQueryService.java
  src/main/java/DNBN/spring/service/CategoryService/CategoryService.java
  src/main/java/DNBN/spring/web/controller/ArticleLikeController.java
  src/main/java/DNBN/spring/web/controller/ArticleSpamController.java
  src/main/java/DNBN/spring/web/controller/CategoryController.java
  src/main/java/DNBN/spring/web/dto/CategoryRequestDTO.java
  src/main/java/DNBN/spring/web/dto/CategoryResponseDTO.java
  src/main/java/DNBN/spring/web/dto/LikeResponseDTO.java
  src/main/java/DNBN/spring/web/dto/LikeStatusResponseDTO.java
  src/main/java/DNBN/spring/web/dto/SpamResponseDTO.java
  src/main/java/DNBN/spring/web/dto/SpamStatusResponseDTO.java
Labels: :sparkles: feature

#32 ✨ [Feat] 좋아요 조회/등록/취소 구현
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/exception/DuplicateCategoryException.java
  src/main/java/DNBN/spring/apiPayload/exception/handler/CategoryHandler.java
  src/main/java/DNBN/spring/domain/Article.java
  src/main/java/DNBN/spring/domain/ArticleLike.java
  src/main/java/DNBN/spring/domain/ArticleLikeId.java
  src/main/java/DNBN/spring/domain/ArticleSpam.java
  src/main/java/DNBN/spring/domain/ArticleSpamId.java
  src/main/java/DNBN/spring/domain/Category.java
  src/main/java/DNBN/spring/repository/ArticleLikeRepository/ArticleLikeRepository.java
  src/main/java/DNBN/spring/repository/ArticleSpamRepository/ArticleSpamRepository.java
  src/main/java/DNBN/spring/repository/CategoryRepository/CategoryRepository.java
  src/main/java/DNBN/spring/service/ArticleLikeService/ArticleLikeQueryService.java
  src/main/java/DNBN/spring/service/ArticleLikeService/ArticleLikeService.java
  src/main/java/DNBN/spring/service/ArticleSpamService/ArticleSpamQueryService.java
  src/main/java/DNBN/spring/service/ArticleSpamService/ArticleSpamService.java
  src/main/java/DNBN/spring/service/CategoryService/CategoryQueryService.java
  src/main/java/DNBN/spring/service/CategoryService/CategoryService.java
  src/main/java/DNBN/spring/web/controller/ArticleLikeController.java
  src/main/java/DNBN/spring/web/controller/ArticleSpamController.java
  src/main/java/DNBN/spring/web/controller/CategoryController.java
  src/main/java/DNBN/spring/web/dto/CategoryRequestDTO.java
  src/main/java/DNBN/spring/web/dto/CategoryResponseDTO.java
  src/main/java/DNBN/spring/web/dto/LikeResponseDTO.java
  src/main/java/DNBN/spring/web/dto/LikeStatusResponseDTO.java
  src/main/java/DNBN/spring/web/dto/SpamResponseDTO.java
  src/main/java/DNBN/spring/web/dto/SpamStatusResponseDTO.java
Labels: :sparkles: feature

#36 ✨[Feat] 카테고리 목록 조회/추가/수정/삭제 구현
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/exception/DuplicateCategoryException.java
  src/main/java/DNBN/spring/apiPayload/exception/handler/CategoryHandler.java
  src/main/java/DNBN/spring/domain/Article.java
  src/main/java/DNBN/spring/domain/ArticleLike.java
  src/main/java/DNBN/spring/domain/ArticleLikeId.java
  src/main/java/DNBN/spring/domain/ArticleSpam.java
  src/main/java/DNBN/spring/domain/ArticleSpamId.java
  src/main/java/DNBN/spring/domain/Category.java
  src/main/java/DNBN/spring/repository/ArticleLikeRepository/ArticleLikeRepository.java
  src/main/java/DNBN/spring/repository/ArticleSpamRepository/ArticleSpamRepository.java
  src/main/java/DNBN/spring/repository/CategoryRepository/CategoryRepository.java
  src/main/java/DNBN/spring/service/ArticleLikeService/ArticleLikeQueryService.java
  src/main/java/DNBN/spring/service/ArticleLikeService/ArticleLikeService.java
  src/main/java/DNBN/spring/service/ArticleSpamService/ArticleSpamQueryService.java
  src/main/java/DNBN/spring/service/ArticleSpamService/ArticleSpamService.java
  src/main/java/DNBN/spring/service/CategoryService/CategoryQueryService.java
  src/main/java/DNBN/spring/service/CategoryService/CategoryService.java
  src/main/java/DNBN/spring/web/controller/ArticleLikeController.java
  src/main/java/DNBN/spring/web/controller/ArticleSpamController.java
  src/main/java/DNBN/spring/web/controller/CategoryController.java
  src/main/java/DNBN/spring/web/dto/CategoryRequestDTO.java
  src/main/java/DNBN/spring/web/dto/CategoryResponseDTO.java
  src/main/java/DNBN/spring/web/dto/LikeResponseDTO.java
  src/main/java/DNBN/spring/web/dto/LikeStatusResponseDTO.java
  src/main/java/DNBN/spring/web/dto/SpamResponseDTO.java
  src/main/java/DNBN/spring/web/dto/SpamStatusResponseDTO.java
Labels: :sparkles: feature

#52 ✨ [Feat] 프로필 이미지 변경
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/DNBN/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/DNBN/spring/aws/s3/AmazonS3Manager.java
  src/main/java/DNBN/spring/domain/ProfileImage.java
  src/main/java/DNBN/spring/service/MemberService/MemberCommandService.java
  src/main/java/DNBN/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/DNBN/spring/web/controller/MemberRestController.java
  src/main/java/DNBN/spring/web/dto/MemberResponseDTO.java
Labels: :sparkles: feature

#65 [HOTFIX] category 오류 수정
  src/main/java/DNBN/spring/service/CategoryService/CategoryService.java
  src/main/java/DNBN/spring/web/dto/CategoryRequestDTO.java
Labels: :ambulance: hotfix

#72 👷 [Ci] CI/CD 구축
  .github/workflows/dev_deploy.yml
Labels: :sparkles: feature, :construction_worker: ci

#76 ✨[Feat] 댓글 및 대댓글 생성
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/DNBN/spring/apiPayload/exception/handler/CommentHandler.java
  src/main/java/DNBN/spring/converter/CommentConverter.java
  src/main/java/DNBN/spring/domain/Comment.java
  src/main/java/DNBN/spring/repository/CommentRepository/CommentRepository.java
  src/main/java/DNBN/spring/repository/RegionRepository/RegionRepository.java
  src/main/java/DNBN/spring/service/CommentService/CommentCommandService.java
  src/main/java/DNBN/spring/service/CommentService/CommentCommandServiceImpl.java
  src/main/java/DNBN/spring/web/controller/CommentController.java
  src/main/java/DNBN/spring/web/dto/CommentRequestDTO.java
  src/main/java/DNBN/spring/web/dto/CommentResponseDTO.java
Labels: :sparkles: feature

#82 ✨ [Feat] 해당 카테고리에 저장된 장소 조회
  src/main/java/DNBN/spring/converter/PlaceConverter.java
  src/main/java/DNBN/spring/repository/SavePlaceRepository/SavePlaceRepository.java
  src/main/java/DNBN/spring/repository/SavePlaceRepository/SavePlaceRepositoryCustom.java
  src/main/java/DNBN/spring/repository/SavePlaceRepository/SavePlaceRepositoryImpl.java
  src/main/java/DNBN/spring/service/PlaceService/PlaceQueryService.java
  src/main/java/DNBN/spring/service/PlaceService/PlaceQueryServiceImpl.java
  src/main/java/DNBN/spring/web/controller/PlaceRestController.java
  src/main/java/DNBN/spring/web/dto/PlaceResponseDTO.java
Labels: :sparkles: feature

#93 ✨ [Feat] 큐레이션 자동 생성
  src/main/java/DNBN/spring/Application.java
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/exception/handler/CurationHandler.java
  src/main/java/DNBN/spring/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/DNBN/spring/converter/CurationConverter.java
  src/main/java/DNBN/spring/domain/Curation.java
  src/main/java/DNBN/spring/domain/mapping/CurationLikeRegion.java
  src/main/java/DNBN/spring/domain/mapping/CurationPlace.java
  src/main/java/DNBN/spring/repository/CurationPlaceRepository/CurationPlaceRepository.java
  src/main/java/DNBN/spring/repository/CurationRepository/CurationRepository.java
  src/main/java/DNBN/spring/repository/LikeRegionRepository/LikeRegionRepository.java
  src/main/java/DNBN/spring/repository/PlaceRepository/PlaceRepository.java
  src/main/java/DNBN/spring/scheduler/CurationScheduler.java
  src/main/java/DNBN/spring/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/DNBN/spring/service/CurationService/CurationCommandService.java
  src/main/java/DNBN/spring/service/CurationService/CurationCommandServiceImpl.java
  src/main/java/DNBN/spring/web/controller/CurationController.java
  src/main/java/DNBN/spring/web/dto/response/CurationResponseDTO.java
Labels: :sparkles: feature

#83 ♻️ [Refactor] 소셜 로그인 정보 쿠키로 내려주기
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/exception/handler/CustomAccessDeniedHandler.java
  src/main/java/DNBN/spring/apiPayload/exception/handler/CustomAuthenticationEntryPoint.java
  src/main/java/DNBN/spring/config/SwaggerConfig.java
  src/main/java/DNBN/spring/config/security/SecurityConfig.java
  src/main/java/DNBN/spring/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/DNBN/spring/config/security/jwt/JwtTokenProvider.java
  src/main/java/DNBN/spring/service/AuthService/AuthCommandService.java
  src/main/java/DNBN/spring/service/AuthService/AuthCommandServiceImpl.java
  src/main/java/DNBN/spring/service/MemberService/MemberCommandService.java
  src/main/java/DNBN/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2FailureHandler.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
  src/main/java/DNBN/spring/web/controller/AuthRestController.java
  src/main/java/DNBN/spring/web/controller/HomeController.java
  src/main/java/DNBN/spring/web/controller/MemberRestController.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :recycle: refactor

#96 ♻️ [Refactor] 카테고리에 저장한 장소 조회 api path 수정 및 페이징 흐름 변경
  src/main/java/DNBN/spring/repository/SavePlaceRepository/SavePlaceRepositoryImpl.java
  src/main/java/DNBN/spring/web/controller/CategoryController.java
  src/main/java/DNBN/spring/web/controller/PlaceRestController.java
Labels: :recycle: refactor

#100 ✨ [Feat] 기본 이미지 URL 목록 조회 API 추가
  src/main/java/DNBN/spring/web/controller/DefaultImageController.java
Labels: :sparkles: feature

#105 ♻️ [Refactor] 게시물 생성 중복 코드 및 AOP 분리
  src/main/java/DNBN/spring/aop/ArticleCreateValidationAspect.java
  src/main/java/DNBN/spring/aop/S3ImageValidationAspect.java
  src/main/java/DNBN/spring/aop/annotation/ValidateS3ImageUpload.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleCommandServiceImpl.java
  src/main/java/DNBN/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/DNBN/spring/web/dto/ArticleResponseDTO.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#109 ✨ [Feat] 댓글 삭제 구현
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/DNBN/spring/domain/Comment.java
  src/main/java/DNBN/spring/service/CommentService/CommentCommandService.java
  src/main/java/DNBN/spring/service/CommentService/CommentCommandServiceImpl.java
  src/main/java/DNBN/spring/web/controller/CommentController.java
Labels: :sparkles: feature

#114 🔨 [Fix] 지도 화면 내 저장된 장소 조회 API - response body 수정
  src/main/java/DNBN/spring/converter/PlaceConverter.java
  src/main/java/DNBN/spring/domain/Place.java
  src/main/java/DNBN/spring/web/dto/PlaceResponseDTO.java
Labels: :hammer: fix
