Repository dongnae-bangnae/BE, pull requests merged in 2025-08, with the labels that each got.

#125 ✨ [Feat] 댓글 알림 조회, 삭제
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/converter/NotificationConverter.java
  src/main/java/DNBN/spring/domain/Notification.java
  src/main/java/DNBN/spring/repository/NotificationRepository/NotificationRepository.java
  src/main/java/DNBN/spring/repository/NotificationRepository/NotificationRepositoryCustom.java
  src/main/java/DNBN/spring/repository/NotificationRepository/NotificationRepositoryImpl.java
  src/main/java/DNBN/spring/service/CommentService/CommentCommandServiceImpl.java
  src/main/java/DNBN/spring/service/NotificationService/NotificationCommandService.java
  src/main/java/DNBN/spring/service/NotificationService/NotificationCommandServiceImpl.java
  src/main/java/DNBN/spring/service/NotificationService/NotificationQueryService.java
  src/main/java/DNBN/spring/service/NotificationService/NotificationQueryServiceImpl.java
  src/main/java/DNBN/spring/web/controller/NotificationRestController.java
  src/main/java/DNBN/spring/web/dto/NotificationResponseDTO.java
Labels: :sparkles: feature

#127 ♻️ [Refactor] CSRF 쿠키 사용하도록
  src/main/java/DNBN/spring/apiPayload/exception/handler/CustomAccessDeniedHandler.java
  src/main/java/DNBN/spring/config/security/SecurityConfig.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#128 ✨ [Feat] 광고 의심 알림 목록 조회 및 삭제 API 구현, 신고 수 20회 이상 일 시 게시글 삭제 로직 추가
  src/main/java/DNBN/spring/converter/NotificationConverter.java
  src/main/java/DNBN/spring/domain/Notification.java
  src/main/java/DNBN/spring/repository/NotificationRepository/NotificationRepositoryCustom.java
  src/main/java/DNBN/spring/repository/NotificationRepository/NotificationRepositoryImpl.java
  src/main/java/DNBN/spring/service/ArticleSpamService/ArticleSpamService.java
  src/main/java/DNBN/spring/service/NotificationService/NotificationQueryService.java
  src/main/java/DNBN/spring/service/NotificationService/NotificationQueryServiceImpl.java
  src/main/java/DNBN/spring/web/controller/NotificationRestController.java
  src/main/java/DNBN/spring/web/controller/PlaceRestController.java
  src/main/java/DNBN/spring/web/dto/NotificationResponseDTO.java
Labels: :sparkles: feature, :recycle: refactor

#130 ✨ [Feat] 게시물 상세 조회 API 구현
  src/main/java/DNBN/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/DNBN/spring/converter/ArticleConverter.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleQueryService.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleQueryServiceImpl.java
  src/main/java/DNBN/spring/web/controller/ArticleController.java
  src/main/java/DNBN/spring/web/dto/ArticleResponseDTO.java
Labels: :sparkles: feature

#133 ✨ [Feat] 게시물 목록 조회
  src/main/java/DNBN/spring/converter/ArticleConverter.java
  src/main/java/DNBN/spring/repository/ArticlePhotoRepository/ArticlePhotoRepository.java
  src/main/java/DNBN/spring/repository/ArticleRepository/ArticleRepository.java
  src/main/java/DNBN/spring/repository/ArticleRepository/ArticleRepositoryCustom.java
  src/main/java/DNBN/spring/repository/ArticleRepository/ArticleRepositoryImpl.java
  src/main/java/DNBN/spring/repository/PlaceRepository/PlaceRepository.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleQueryService.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleQueryServiceImpl.java
  src/main/java/DNBN/spring/web/controller/ArticleController.java
  src/main/java/DNBN/spring/web/dto/ArticleResponseDTO.java
  src/main/resources/application.yml
  src/test/java/DNBN/spring/service/ArticleService/ArticleQueryServiceImplTest.java
Labels: :sparkles: feature, 🧪 test

#137 ✨ [Feat] 댓글 조회
  src/main/java/DNBN/spring/aop/CommentValidationAspect.java
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/DNBN/spring/domain/Comment.java
  src/main/java/DNBN/spring/repository/CommentRepository/CommentRepository.java
  src/main/java/DNBN/spring/repository/CommentRepository/CommentRepositoryCustom.java
  src/main/java/DNBN/spring/repository/CommentRepository/CommentRepositoryImpl.java
  src/main/java/DNBN/spring/service/CommentService/CommentQueryService.java
  src/main/java/DNBN/spring/service/CommentService/CommentQueryServiceImpl.java
  src/main/java/DNBN/spring/web/controller/CommentController.java
  src/main/java/DNBN/spring/web/dto/CommentCursorResponseDTO.java
  src/main/java/DNBN/spring/web/dto/CommentListCursorResponseDTO.java
Labels: :sparkles: feature

#136 ✨ [Feat] 게시물 수정
  src/main/java/DNBN/spring/aop/ArticleCreateValidationAspect.java
  src/main/java/DNBN/spring/aop/ArticleValidationAspect.java
  src/main/java/DNBN/spring/aop/annotation/ValidateArticle.java
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/DNBN/spring/domain/Article.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleCommandService.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleCommandServiceImpl.java
  src/main/java/DNBN/spring/web/controller/ArticleController.java
  src/main/java/DNBN/spring/web/dto/ArticleUpdateRequestDTO.java
Labels: :sparkles: feature

#144 🔨 [Fix] .com을 .site로 수정
  src/main/java/DNBN/spring/service/OAuth2/OAuth2FailureHandler.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
Labels: :ambulance: hotfix, :hammer: fix

#147 🔨 [Fix] sendRedirect에 www. 추가
  src/main/java/DNBN/spring/service/OAuth2/OAuth2FailureHandler.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
Labels: :ambulance: hotfix, :hammer: fix

#142 ♻️ [Refactor] 게시물/댓글 검증 로직을 역할에 맞게 통합 및 분리
  src/main/java/DNBN/spring/aop/ArticleValidationAspect.java
  src/main/java/DNBN/spring/aop/CommentValidationAspect.java
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/DNBN/spring/domain/Comment.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleCommandServiceImpl.java
  src/main/java/DNBN/spring/service/CommentService/CommentCommandServiceImpl.java
  src/main/java/DNBN/spring/validation/ContentLengthValidator.java
  src/main/java/DNBN/spring/validation/TitleLengthValidator.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#155 ✨ [Feat] 닉네임 중복 확인
  src/main/java/DNBN/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DNBN/spring/repository/MemberRepository/MemberRepository.java
  src/main/java/DNBN/spring/service/MemberService/MemberCommandServiceImpl.java
Labels: :sparkles: feature, :ambulance: hotfix, :hammer: fix

#162 ♻️ [Refactor] sameSite를 None으로 수정
  src/main/java/DNBN/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2FailureHandler.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
  src/main/java/DNBN/spring/web/controller/AuthRestController.java
  src/main/resources/application.yml
Labels: :ambulance: hotfix, :recycle: refactor, :hammer: fix

#169 🛠️ [Test] CSRF토큰 중복 문제 해결
  src/main/java/DNBN/spring/service/AuthService/AuthCommandService.java
  src/main/java/DNBN/spring/service/AuthService/AuthCommandServiceImpl.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
  src/main/java/DNBN/spring/web/controller/AuthRestController.java
Labels: :bug: bug, :ambulance: hotfix, :hammer: fix

#189 🧪 [Test] JSESSIONID 삭제 코드 복구
  src/main/java/DNBN/spring/service/OAuth2/OAuth2FailureHandler.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
Labels: :ambulance: hotfix

#191 🚑 [Hotfix] csrf 토큰 중복 문제 해결
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
  src/main/java/DNBN/spring/web/controller/AuthRestController.java
Labels: :ambulance: hotfix

#192 🚑 [Hotfix] 성공핸들러에서 csrf 쿠키 직접 내려주기
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
Labels: :ambulance: hotfix

#193 🚑 [Hotfix] 성공핸들러에서 csrf 쿠키 이름 문제 해결
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
Labels: :ambulance: hotfix

#194 🚑 [Hotfix] csrf 쿠키 저장
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
Labels: :ambulance: hotfix

#211 ♻️ [Refactor] sameSite값을 Lax로
  src/main/java/DNBN/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2FailureHandler.java
  src/main/java/DNBN/spring/service/OAuth2/OAuth2SuccessHandler.java
  src/main/java/DNBN/spring/web/controller/AuthRestController.java
Labels: :recycle: refactor

#216 ♻️ [Refactor] ArticleValidationAspect 메소드 순서 정리 및 그룹화
  src/main/java/DNBN/spring/aop/ArticleValidationAspect.java
Labels: :recycle: refactor

#219 token null 오류 수정
  src/main/java/DNBN/spring/web/controller/ArticleLikeController.java
Labels: :bug: bug, :ambulance: hotfix

#226 🔨 [Fix] 해당 장소 저장된 카테고리 삭제 후 장소 저장 로직 수정
  src/main/java/DNBN/spring/repository/SavePlaceRepository/SavePlaceRepository.java
  src/main/java/DNBN/spring/service/PlaceService/PlaceCommandServiceImpl.java
Labels: :hammer: fix

#234 🧪 [Test] ArticleCommandService 단위 테스트 추가
  src/main/java/DNBN/spring/domain/Article.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleCommandServiceImpl.java
  src/test/java/DNBN/spring/service/ArticleService/ArticleCommandServiceImplTest.java
Labels: 🧪 test

#238 🔨 [Fix] 게시물 생성 요청의 regionId 필드 제거 (미등록 장소 포함)
  src/main/java/DNBN/spring/repository/RegionRepository/RegionRepositoryCustom.java
  src/main/java/DNBN/spring/repository/RegionRepository/RegionRepositoryImpl.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleCommandServiceImpl.java
  src/main/java/DNBN/spring/web/dto/request/ArticleRequestDTO.java
  src/main/java/DNBN/spring/web/dto/request/ArticleWithLocationRequestDTO.java
Labels: :hammer: fix

#240 ✨ [Feat] 게시물 생성 시 좌표 기반 지역 검색 로직 추가
  src/main/java/DNBN/spring/repository/RegionRepository/RegionRepositoryCustom.java
  src/main/java/DNBN/spring/repository/RegionRepository/RegionRepositoryImpl.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleCommandServiceImpl.java
Labels: :sparkles: feature

#246 🔨 [Fix] 이미지 업로드 예외 처리 개선
  src/main/java/DNBN/spring/aws/s3/AmazonS3Manager.java
  src/main/java/DNBN/spring/service/ArticleService/ArticleImageService.java
Labels: :hammer: fix

#247 ✨ [Feat] 메인 이미지 필수 검증 추가
  src/main/java/DNBN/spring/service/ArticleService/ArticleImageService.java
Labels: :sparkles: feature
